### ISSUE TITLE
Defect: Not able to select the option from the main menu

### ISSUE THREAD

**Issue by ssreddy2020** [dfresh613/MSCS721-RoomScheduler#6]
Hi, 
Not able to select the option from the main menu. Please find the attached screenshot for reference.

**Steps:** Run the application. In console window -> select option from main menu.
**Input:** Any numeric value between 1 and 5. Entered 1 as input.
**Expected Result: *_It has to call “Add a Room Method”.
*_Actual Result:** Invalid input. Please enter numeric selection between 1-5. Displaying the main menu selection again.

Thanks,
Sandeep
![error1](https://cloud.githubusercontent.com/assets/16215408/13158747/57866f70-d65c-11e5-8b4d-b1ae81ed4ada.PNG)

**Comment by dfresh613** [comment]
this occurs when there is white space added before or after the number input. I need to trim the whitespace before and after the input. Good find!

**Comment by dfresh613** [comment]
Trimmed whitespace to fix this defect
