### ISSUE TITLE
Additional Enhancement: Scheduling a Room

### ISSUE THREAD

**Issue by ssreddy2020** [dfresh613/MSCS721-RoomScheduler#9]
Hi,

**SUMMARY:** When scheduling a room, if time conflict occurs for the same room then display the rooms which are not scheduled for any meeting.
**Input:** Select option 3 from the main menu. Schedule a meeting for some room from 10AM to 2PM. 
once the room is scheduled, select option 3 from main menu and schedule a meeting for the same room from 1PM to 4PM. 
**Expected Result:** An alert message should be displayed saying that ‘Time conflict has occurred’
 And also it has to display the rooms which are not scheduled during that time period/ non-scheduled rooms.

Thanks,
Sandeep

**Comment by dfresh613** [comment]
Enhancement added
